[theme]
base                = "dark"
primaryColor        = "#f5c518"
backgroundColor     = "#0d0d0d"
secondaryBackgroundColor = "#161616"
textColor           = "#f0f0f0"
font                = "sans serif"

[server]
headless = true
